### ISSUE TITLE
Highlighting multiline comments

### ISSUE THREAD

**Issue by pchaigno** [TakeshiTseng/atom-language-p4#2]
This Atom grammar is now used on github.com to [highlight P4 files](https://github.com/github/linguist/blob/74a71fd90dc5124c5479f792101f385723fa79c1/samples/P4/mirror_acl.p4). Unfortunately, the grammar doesn't recognize multiline comments, causing [some files to be incorrectly highlighted](https://github.com/github/linguist/blob/74a71fd90dc5124c5479f792101f385723fa79c1/samples/P4/l2.p4).

**Comment by Yi-Tseng** [comment]
Hi,

Sorry for late reply

I'll fix this ASAP

**Comment by Yi-Tseng** [comment]
Hi,

I think I fixed(commit bd5a8c), can you try again ?

Thanks.

**Comment by pchaigno** [comment]
Great! [It looks way better](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FTakeshiTseng%2Fatom-language-p4%2Fblob%2Fmaster%2Fgrammars%2Fp4.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fgithub%2Flinguist%2Fblob%2F74a71fd90dc5124c5479f792101f385723fa79c1%2Fsamples%2FP4%2Fl2.p4&code=).
It should apply on all github.com with the next release of Linguist.
